# Generated by Django 5.1.6 on 2025-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='creatives/%Y/%m/%d/')),
                ('global_status', models.CharField(choices=[('green', 'Compliant'), ('yellow', 'Attention Required'), ('red', 'Non-Compliant')], default='yellow', max_length=10)),
                ('result_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
